// Shared plain-English definitions for stat abbreviations, used to power native
// title-attribute tooltips wherever a stat label appears. One dictionary so the
// wording can't drift between pages.
module.exports = {
  AVG: 'Batting average — hits divided by at-bats',
  OBP: 'On-base percentage — how often a batter reaches base via hit, walk, or hit-by-pitch',
  SLG: 'Slugging percentage — total bases divided by at-bats',
  OPS: 'On-base plus slugging (OBP + SLG) — a quick combined measure of a hitter\'s value',
  HR: 'Home runs',
  RBI: 'Runs batted in',
  R: 'Runs scored',
  H: 'Hits',
  '2B': 'Doubles',
  '3B': 'Triples',
  BB: 'Walks (bases on balls)',
  SO: 'Strikeouts',
  SB: 'Stolen bases',
  AB: 'At-bats',
  PA: 'Plate appearances',
  G: 'Games played',
  ERA: 'Earned run average — earned runs allowed per 9 innings pitched',
  WHIP: 'Walks plus hits per inning pitched',
  IP: 'Innings pitched',
  W: 'Wins',
  L: 'Losses',
  'W-L': 'Wins-Losses',
  SV: 'Saves',
  ER: 'Earned runs allowed',
  'R/G': 'Runs scored per game',
  'RA/G': 'Runs allowed per game',
  'HR/G': 'Home runs per game',
  'RUN DIFF': 'Run differential — runs scored minus runs allowed',
  FPCT: 'Fielding percentage — (putouts + assists) / (putouts + assists + errors)',
  PCT: 'Winning percentage — wins divided by games played',
  GB: 'Games back — how many games behind the league leader',
  'D/N': 'Day or night game',
};
